version: '3.3'

services:
  the_app:
    build: ./solutions
    # command: python manage.py runserver 0.0.0.0:3000
    volumes:
      - ./solutions/:/app/
    ports:
      - 3000:3000
    # env_file:
    #   - ./sterkfontein-server/.env.dev

  # proxy:
  #   build: ./nginx
  #   restart: always
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - the_app
  
#   db:
#     image: postgis/postgis:13-3.2-alpine
#     volumes:
#       - postgres_data:/var/lib/postgres_data/
#     environment:
#       - POSTGRES_USER=sterkfontein
#       - POSTGRES_PASSWORD=sterkfonteinadmin
#       - POSTGRES_DB=sterkfontein_rdbms

volumes:
  # postgres_data:
  the_app: